### ISSUE TITLE
Searching for content could have more accuracy

### ISSUE THREAD

**Issue by joho1968** [julien-nc/integration_mattermost#12]
Excellent integration! :metal: 

If I enable searching for content in Mattermost from Nextcloud, I see Mattermost posts matching the text, so far so good. But there are two issues here, IMHO:

1. If the matching text is in a "private chat" between two people, I get a "Team not found" when I click on it (after being re-directed to Mattermost)
2. If the matching text is in a "normal channel", I get sent to the channel, but not to the actual matching post.

**Comment by julien-nc** [comment]
1. Quite bad implementation on the Mattermost side: the link to a "Direct messages" conversation requires a team name but none is provided in the channel information and any team name works...
2. Thankfully there are permalinks in Mattermost. They are now the link targets of the dashboard items and of the search result items :heavy_check_mark: (permalinks also include a team name and we can put any valid team for a direct message :-1: )

Included in [v1.0.3-2-nightly](https://github.com/julien-nc/integration_mattermost/releases/download/v1.0.3-2-nightly/integration_mattermost-1.0.3-2-nightly.tar.gz) as well.

**Comment by joho1968** [comment]
Good findings ... you may want to reach out to Mattermost about this, their developer community seems to be pretty active and awake in general.
