### ISSUE TITLE
Open Mattermost in new tab/window when clicked from the App-Menu

### ISSUE THREAD

**Issue by luc-ass** [julien-nc/integration_mattermost#18]
First of all a huge Thank You for this integration.

I was wondering, if it wouldn't be handy, if Mattermost opened in a separate window, when clicked on the App-Menu (top menu). As of now the link redirects me to Mattermost and navigating back to NextCloud can take quite some time.

Cheers, Lucas

**Comment by julien-nc** [comment]
Hey, thanks for the suggestion. I did it for other apps but not this one for some reason.

I remember it didn't work in some of my test instances but I didn't get why. Now it seems to work fine on NC 25 and 26.
