### ISSUE TITLE
Mattermost does not load channels

### ISSUE THREAD

**Issue by piratPavel** [julien-nc/integration_mattermost#7]
I got the Mattermost plugin working on the first try.
What doesn't work is loading the channel from Mattermost and thus not being able to send the file/link to it.

**Comment by julien-nc** [comment]
Hi. Thanks for the bug report. I need more information:
* Are you using v1.0.1?
* Is there any error in the browser Javascript console? (F12 -> Console tab)
* Is there any error in the server log? (nextcloud.log)

**Comment by piratPavel** [comment]
Hey. Hey. You're welcome, I'll try to answer

Are you using version 1.0.1?
Yes, it does this in version 1.01 as well.
![2022-11-09 10 21 44 cloud bischofstein cz 019685f0a492](https://user-images.githubusercontent.com/67592345/200793066-7d1d6e7c-d43f-479d-b553-ca654e2505da.jpg)

Is there a bug in the browser's Javascript console? (F12 -> Console tab)
Yes, see picture
![2022-11-09 10 23 40 cloud bischofstein cz a545e7835e01](https://user-images.githubusercontent.com/67592345/200792932-1237e83b-a6ac-4199-99e6-4f2179a03209.jpg)

Is there any error in the server log? (nextcloud.log)
It doesn't want to display the log on my desktop, everything else displays, but the log entries unfortunately don't.

**Comment by julien-nc** [comment]
I need the detailed javascript error. Could you unfold it in the console and check the value of r.response.data?

**Comment by piratPavel** [comment]
![2022-11-09 10 57 09 cloud bischofstein cz f7699963d16e](https://user-images.githubusercontent.com/67592345/200799864-59cd4fa6-b1fe-47f1-b139-ee49e7f37e16.jpg)
![2022-11-09 10 56 48 cloud bischofstein cz ea2480f4bb1d](https://user-images.githubusercontent.com/67592345/200799874-a4513204-6f8f-47b7-88f9-f63cee4ebccc.jpg)
![2022-11-09 10 56 27 cloud bischofstein cz 63869e4a6f73](https://user-images.githubusercontent.com/67592345/200799877-4900850d-0bd0-4456-a12c-91397a5842ce.jpg)
![2022-11-09 10 57 26 cloud bischofstein cz 599ba081f03b](https://user-images.githubusercontent.com/67592345/200799879-664fe461-a24c-4cf3-94d6-5e3844b0bf42.jpg)

**Comment by julien-nc** [comment]
Thanks. So Mattermost is giving you a 403 response when trying to get the channels.

* How do you authenticate in the integration? (OAuth, personal token or login/password)
* What is the Mattermost server version?

**Comment by piratPavel** [comment]
How do you verify yourself in the integration? (OAuth, personal token or login/password).
username/password

What is the version of the Mattermost server?
I need to verify, it will take a while

**Comment by piratPavel** [comment]
So the version on the server is: 7.3.0 (Build 7.3.0-rc3)
Database. postgres

**Comment by piratPavel** [comment]
Thank you for the info.

I'm an admin on the nextcloud side
On the mattermost side I am just a user, but the admin reported the same error to me.

I wish you success

**Comment by julien-nc** [comment]
Fix is included in v1.0.2 which is now released. Thanks again for helping to figure out this one.

One benefit from the fix: It is now possible to send files to "Direct messages" user-user conversations. When using the proper API endpoints, it is possible to get those conversations as well so I adjusted the frontend to list those as well (with the user avatar in the multiselect :grin:).

This also fixes the item links in the dashboard widget and the search results.

Before closing this, let's wait until you have a chance to try v1.0.2 and hopefully confirm it works now.

**Comment by piratPavel** [comment]
**Bingo, confirm functionality in version 1.0.2**

![2022-11-09 17 51 26 cloud bischofstein cz 342438260b5c](https://user-images.githubusercontent.com/67592345/200892264-a7d14f75-05fc-4474-8b17-be5f9d5f394e.jpg)
.........................................................................................................................................................................................................

![2022-11-09 17 52 18 cloud bischofstein cz 42d986578ade](https://user-images.githubusercontent.com/67592345/200892315-f26e83f9-9978-4a34-97f9-ebff6360e3e9.jpg)

Thanks for the speed and let's keep the error messages to a minimum.
Have a nice day
