### ISSUE TITLE
Timeout when connecting to Mattermost

### ISSUE THREAD

**Issue by ateuber** [julien-nc/integration_mattermost#8]
I'm getting a timeout after 30s when connecting to Mattermost. I'm trying to use OAuth. The Mattermost version is 7.4.1.

**Comment by julien-nc** [comment]
Hi. Thanks for the bug report.
I need more information:
* Are you using v1.0.1?
* What is your authentication method? (OAuth, personal token or login/password)

All auth methods work fine on my side with Mattermost 7.4.0 deployed with https://github.com/mattermost/docker using the `mattermost/mattermost-enterprise-edition:7.4` image.

**Comment by ateuber** [comment]
- I'm using v1.0.1
- I'm using the `mattermost/mattermost-team-edition:release-7.4` image
- I'm using OAuth, so filled out `settings/admin/connected-accounts` and set the `Redirect URI` mentioned there in Mattermost.
- When connecting, it adds an OAuth application in Mattermost (in Profile -> Security)
- (First I tried it via personal access token and login/password, but got an error that I should enable Javascript, which was enabled, though)

I wonder if this could be a problem with the firewall and reverse proxy between Mattermost and UCS? Any idea how to test if this is even a problem with this integration?

**Comment by ateuber** [comment]
It was another networking problem, just figured it out myself. Thank you anyway! :-)
