### ISSUE TITLE
[Feature Request] Sending internal links

### ISSUE THREAD

**Issue by seyfeb** [julien-nc/integration_mattermost#9]
It would be nice to have the ability to choose between sharing public and internal links!

**Comment by seyfeb** [comment]
I'll try to see if I find the time to get a Mattermost instance running locally for testing. Anyway, thx for taking action so quickly!

**Comment by julien-nc** [comment]
You don't need a local Mattermost instance, you can use the same Mattermost as you used before. The integration_mattermost nightly build is not destructive, you can use it safely.

**Comment by seyfeb** [comment]
I just tested this for NC 24.0.6 and it seems to work well (both public and private links).

**Comment by julien-nc** [comment]
Thanks for the feedback.
v1.0.3 is out.
